import {
  Landmark,
  Wallet,
  CreditCard,
  Banknote,
  PiggyBank,
  TrendingUp,
  CircleDollarSign,
  HandCoins,
  Building2,
  Vault,
  BadgeDollarSign,
  Coins,
  Receipt,
  Target,
  Package,
} from "lucide-react";

export const NAV_SECTIONS = [
  {
    label: "가계부",
    items: [
      {
        id: "dashboard",
        label: "대시보드",
        path: "/",
        icon: "LayoutDashboard",
      },
      { id: "accounts", label: "계좌", path: "/accounts", icon: "Landmark" },
      {
        id: "transactions",
        label: "거래내역",
        path: "/transactions",
        icon: "Receipt",
      },
      {
        id: "statistics",
        label: "통계",
        path: "/statistics",
        icon: "BarChart3",
      },
      { id: "budget", label: "예산", path: "/budget", icon: "Wallet" },
      {
        id: "fixed-expenses",
        label: "고정지출",
        path: "/fixed-expenses",
        icon: "CalendarClock",
      },
      {
        id: "categories",
        label: "카테고리",
        path: "/categories",
        icon: "Tag",
      },
      {
        id: "annual-report",
        label: "연간 리포트",
        path: "/annual-report",
        icon: "CalendarRange",
      },
    ],
  },
  {
    label: "할일",
    items: [
      { id: "tasks", label: "할일", path: "/tasks", icon: "ListTodo" },
      {
        id: "task-categories",
        label: "카테고리",
        path: "/task-categories",
        icon: "Tag",
      },
    ],
  },
];

export const ACCOUNT_TYPE_LABELS = {
  checking: "입출금",
  savings: "저축",
  credit_card: "신용카드",
  cash: "현금",
  investment: "투자",
};

export const ACCOUNT_TYPE_ORDER = [
  "checking",
  "savings",
  "investment",
  "credit_card",
  "cash",
];

export const ACCOUNT_ICONS = [
  "Landmark",
  "Wallet",
  "CreditCard",
  "Banknote",
  "PiggyBank",
  "TrendingUp",
  "CircleDollarSign",
  "HandCoins",
  "Building2",
  "Vault",
  "BadgeDollarSign",
  "Coins",
  "Receipt",
  "Target",
  "Package",
];

export const ACCOUNT_ICON_MAP = {
  Landmark,
  Wallet,
  CreditCard,
  Banknote,
  PiggyBank,
  TrendingUp,
  CircleDollarSign,
  HandCoins,
  Building2,
  Vault,
  BadgeDollarSign,
  Coins,
  Receipt,
  Target,
  Package,
};

export const ACCOUNT_COLORS = [
  "#0046FF",
  "#3182F6",
  "#FFCD00",
  "#6DD4B4",
  "#F4845F",
  "#A78BFA",
  "#7DD3FC",
  "#FDA4AF",
  "#FCD34D",
  "#6B7280",
  "#C4A44A",
  "#EF4444",
  "#10B981",
  "#8B5CF6",
  "#EC4899",
];

export const INSTITUTIONS = [
  // 🇺🇸 미국
  "Chase",
  "Bank of America",
  "Wells Fargo",
  "Citibank",
  "Capital One",
  "US Bank",
  "PNC Bank",
  "TD Bank",
  "American Express",
  "Discover",
  "Goldman Sachs",
  "Charles Schwab",
  "Fidelity",
  "Ally Bank",
  "SoFi",
  "Marcus",
  "Navy Federal",
  "USAA",
  // 🇰🇷 한국
  "국민은행",
  "신한은행",
  "하나은행",
  "우리은행",
  "농협은행",
  "기업은행",
  "SC제일은행",
  "카카오뱅크",
  "토스뱅크",
  "케이뱅크",
  "새마을금고",
  "신협",
  "우체국",
  "삼성카드",
  "현대카드",
  "롯데카드",
  "BC카드",
];
